# Generated by Django 4.2.3 on 2023-07-19 15:11

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Hosts',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('address', models.CharField(max_length=100)),
                ('description', models.CharField(blank=True, max_length=100, null=True)),
            ],
            options={
                'verbose_name': 'Host Status',
                'verbose_name_plural': 'Hosts Status',
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='MapsNode',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, null=True)),
                ('lat', models.FloatField(null=True)),
                ('long', models.FloatField(null=True)),
                ('type', models.CharField(max_length=100, null=True)),
            ],
            options={
                'verbose_name': 'Maps Node',
                'verbose_name_plural': 'Maps Node',
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='NetworkDevice',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, null=True)),
                ('ip_address', models.GenericIPAddressField(null=True)),
                ('status', models.BooleanField(blank=True, null=True)),
                ('node', models.ForeignKey(null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='main.mapsnode')),
            ],
            options={
                'verbose_name': 'Network Device',
                'verbose_name_plural': 'Network Devices',
                'ordering': ['name'],
            },
        ),
        migrations.AddField(
            model_name='mapsnode',
            name='devices',
            field=models.ManyToManyField(to='main.networkdevice'),
        ),
    ]
