# Generated by Django 4.2.3 on 2023-07-19 15:43

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0001_initial'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Hosts',
        ),
    ]
