# Generated by Django 4.2.3 on 2023-07-19 16:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0002_delete_hosts'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='networkdevice',
            name='node',
        ),
        migrations.AddField(
            model_name='networkdevice',
            name='lat',
            field=models.FloatField(null=True),
        ),
        migrations.AddField(
            model_name='networkdevice',
            name='latency',
            field=models.IntegerField(blank=True, default=0, null=True),
        ),
        migrations.AddField(
            model_name='networkdevice',
            name='long',
            field=models.FloatField(null=True),
        ),
        migrations.AddField(
            model_name='networkdevice',
            name='type',
            field=models.CharField(choices=[('Router', 'Router'), ('Switch Manage', 'Switch Manage'), ('Switch UnManage', 'Switch UnManage'), ('AP', 'AP')], max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='networkdevice',
            name='status',
            field=models.BooleanField(blank=True, default=False, null=True),
        ),
        migrations.DeleteModel(
            name='MapsNode',
        ),
    ]
