# Generated by Django 4.2.4 on 2023-08-28 12:19

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0003_remove_networkdevice_node_networkdevice_lat_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='networkdevice',
            old_name='status',
            new_name='last_status',
        ),
    ]
