# Generated by Django 4.2.4 on 2023-08-30 07:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0004_rename_status_networkdevice_last_status'),
    ]

    operations = [
        migrations.AddField(
            model_name='networkdevice',
            name='fail_check',
            field=models.IntegerField(blank=True, default=0, null=True),
        ),
    ]
