# Generated by Django 4.2.4 on 2023-08-31 04:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0005_networkdevice_fail_check'),
    ]

    operations = [
        migrations.AddField(
            model_name='networkdevice',
            name='daily_reboot_status',
            field=models.BooleanField(blank=True, default=False, null=True),
        ),
    ]
