# Generated by Django 4.2.4 on 2023-08-31 04:16

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0006_networkdevice_daily_reboot_status'),
    ]

    operations = [
        migrations.RenameField(
            model_name='networkdevice',
            old_name='daily_reboot_status',
            new_name='daily_restart_status',
        ),
    ]
