# Generated by Django 4.2.4 on 2023-08-31 06:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0007_rename_daily_reboot_status_networkdevice_daily_restart_status'),
    ]

    operations = [
        migrations.CreateModel(
            name='SummaryRestart',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('summary', models.CharField(blank=True, max_length=300, null=True)),
                ('time', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'verbose_name': 'Summary Restart',
                'verbose_name_plural': 'Summarys Restart',
                'ordering': ['summary'],
            },
        ),
    ]
