# Generated by Django 4.2.4 on 2023-09-07 06:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0008_summaryrestart'),
    ]

    operations = [
        migrations.CreateModel(
            name='RestartStatus',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('status', models.BooleanField(blank=True, default=False, null=True)),
            ],
            options={
                'verbose_name': 'Status Restart',
                'verbose_name_plural': 'Status Restart',
                'ordering': ['status'],
            },
        ),
        migrations.AlterModelOptions(
            name='summaryrestart',
            options={'ordering': ['summary'], 'verbose_name': 'Summary Restart', 'verbose_name_plural': 'Summaries Restart'},
        ),
    ]
